// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQtBeGexjeabNgVR4ZtlVClghjzqaviPY',
    appId: '1:655762591335:android:b7670d4cf70f84d2730ec2',
    messagingSenderId: '655762591335',
    projectId: 'beauty-salon-5d6bb',
    storageBucket: 'beauty-salon-5d6bb.appspot.com',
    // measurementId: 'G-HYLR3KGRNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQtBeGexjeabNgVR4ZtlVClghjzqaviPY',
    appId: '1:655762591335:android:b7670d4cf70f84d2730ec2',
    messagingSenderId: '655762591335',
    projectId: 'mess-attendance-d353d',
    storageBucket: 'mess-attendance-d353d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT_ta3B9x7xhOxiPUcu8DIvmhKj7pUcCk',
    appId: '1:485894622604:ios:99c978dc90e7e0dd599aa9',
    messagingSenderId: '485894622604',
    projectId: 'bank-app-ae68e',
    storageBucket: 'bank-app-ae68e.appspot.com',
    // iosClientId:
    //     '816831984722-rnmhv8pt2rrq4b3tpi1i6o72rddqo074.apps.googleusercontent.com',
    // iosBundleId: 'com.example.flutterAntonxBoilerplate',
  );
}
